### ISSUE TITLE
Widgets overlay each other

### ISSUE THREAD

**Issue by SteveKej** [psifidotos/nowdock-panel#1]
I tried the nowdock panel and master nowdock and found that some widgets overlay each other.

These are the widgets I added (left to right) Application Menu - Folder View - Activity Pager - Desktop Pager - Now Dock - Weather Widget - System Tray - Key State
The panel ends up looking like this with no mouseover:
![image](https://cloud.githubusercontent.com/assets/1503819/18038148/e1054ade-6d8b-11e6-98c9-5c36181b04e1.png)

Also some widgets animate only when the now-dock widget is animating.  A direct mouseover doesn't animate it.  Here's the Desktop Pager part-animating by being close to the now-dock.
![image](https://cloud.githubusercontent.com/assets/1503819/18038191/9ede9c36-6d8c-11e6-8eab-d7db58ddf12e.png)
Here's the same with the mouse over the Desktop Pager:
![image](https://cloud.githubusercontent.com/assets/1503819/18038223/189b30f2-6d8d-11e6-956c-6da9caf92c25.png)
The same thing happens with the weather widget on the right side (hidden underneath the system tray).

The system tray also overlays widgets on either side of it.  I will point out that I have done this: https://forum.kde.org/viewtopic.php?f=289&t=131736#p359730 Just in case that has any relation.

Hope it could help!

**Comment by psifidotos** [comment]
I will investigate it Steve,

as it appears the main issue is with plasmoids that force their orthogonal layout.

With the current implementation only plasmoids with rectangular layout in small sizes are supported, e.g. places, weather, clocks, notes

I 'll try to support also the rest, at least to be shown and zoomed correctly...

**Comment by psifidotos** [comment]
![image](https://cloud.githubusercontent.com/assets/2216474/18056165/7700c0ae-6e13-11e6-8b7d-62c08d3b9585.png)

can you please check master again?
The situation is the following... Plasmoids have not implemented in a way to grow as Now Dock does... :)

What I have done is that the Now Dock Panel trys to position all plasmoids correctly... After that it investigates them to see if they can support hovering effect if they cant it disables the hovering effect for them... Special care has been made for the system tray...

I would like a lot to have your feedback in this update....

**Comment by SteveKej** [comment]
Hi,

Thanks for the explanation.  I've downloaded and installed from master again and it is now much improved :)
![image](https://cloud.githubusercontent.com/assets/1503819/18062260/f49faa52-6e1d-11e6-9151-9a66a10b8d8f.png)

I'm only getting zooming animations on nowdock itself though.  While I was playing with it, the Application Launcher, Folderview and some other widgets were zooming for a while, but now they're remaining static.  The weather widget starts to animate when I hover over the end of nowdock, but remains static when I hover over it directly. 
![image](https://cloud.githubusercontent.com/assets/1503819/18062967/ea6c5ff0-6e20-11e6-9503-320d8c212792.png)

Another issue with the weather widget (https://www.kde-look.org/p/998917/).  If I use it's compact or vertical layout then all's fine, but it's horizontal layout still overlays the system tray.  It doesn't do this in standard panel.
![image](https://cloud.githubusercontent.com/assets/1503819/18062594/5f3f42cc-6e1f-11e6-9648-cf651c1c215a.png)

Hope this is useful to you.  Great job!

**Comment by psifidotos** [comment]
Steve can you please check that for the plasmoids that stopped zooming you have Locked State for your widgets in your desktop? Animation for applets is not working in unlocked state...

Concerning the weather widget I will take a look to see what is going on... How it draws itself and catch its case... :)

**Comment by SteveKej** [comment]
Hi Michail,

Ahh that was the case.  It was indeed unlocked.  Locking widgets brings back the zoom.

Cheers!

**Comment by psifidotos** [comment]
Perfect.... :-)
:+1:

**Comment by psifidotos** [comment]
![image](https://cloud.githubusercontent.com/assets/2216474/18071067/5476aba0-6e5b-11e6-9aab-e3e86890ad33.png)

in master now... I try to support one axis scaling for some plasmoids... This should fix the weather plasmoid layout and it supports zooming also...

**Comment by SteveKej** [comment]
Great :)  That seems to have fixed the overlaying issue with weather widget's horizontal layout.

Something I've been wondering.  How do you feel about having an option to not animate widgets, only the nowdock? I'm using the Breeze Dark Desktop Theme and 'Windows Can Cover' panel setting.  Some widgets are text based or monochrome and when they 'grow' out of the the 'fake' panel they're hard to see against a light background, such as this webpage in a browser.

**Comment by psifidotos** [comment]
Happy for this working for you!

If you want only the now dock plasmoid animations and not widgets animation why not use a regular panel and insert the now dock plasmoid in it?

**Comment by SteveKej** [comment]
Oh yes!  Just put it down to me having a 'senior moment' :D

**Comment by psifidotos** [comment]
:), happens to me also offently !!!

I dont know though if it would be useful to enable the user to lock zoom effect independently,
e.g. locking the weather applet, places, or notes... It could be useful...

**Comment by psifidotos** [comment]
![spectacle y16837](https://cloud.githubusercontent.com/assets/2216474/18090630/4e5c7920-6ece-11e6-830e-998433b8aee2.png)

I uploaded this in master... 
You can lock any widget you want in order to not zoom itself...

**Comment by SteveKej** [comment]
That's very cool!  Working great here :)

**Comment by psifidotos** [comment]
my pleasure... :)

**Comment by psifidotos** [comment]
this must have been fixed with recent updates...
