### ISSUE TITLE
Fit Icons to Panel

### ISSUE THREAD

**Issue by psifidotos** [psifidotos/nowdock-panel#10]
converation based on: https://github.com/psifidotos/nowdock-plasmoid/issues/26

**Comment by psifidotos** [comment]
please check this from **master** branches for plasmoid and panel... I think it has been improved a lot!!! :) very complex piece of code this one, I had difficult time....

**Comment by AndydeCleyre** [comment]
@psifidotos Thanks!

Yes, this is working pretty well now. I've disabled my desktop edge switching so that I can play more with this.

While I'm still hoping for a handful of developments, I think I would go ahead and try switching from Plank if I could get transparency working.

![screenshot_20160909_144834](https://cloud.githubusercontent.com/assets/1787385/18399152/b3598788-769d-11e6-8022-e9fb5763f07d.png)

**Comment by psifidotos** [comment]
@AndydeCleyre  my pleasure...

> While I'm still hoping for a handful of developments

you... and all of us... especially in the plasma technologies side... :-)

>  if I could get transparency working.

I dont think you are going to have any issue... if you need any help for this, just ping me...

**Comment by AndydeCleyre** [comment]
@psifidotos I need help for that :).

I used `plasma-transparent-panel.py.v0.2.2`:

``` bash
python transparentpanel.py default West
```

And then chose the plasma theme as shown above.

**Comment by psifidotos** [comment]
@AndydeCleyre dont use the command line...

just click on **transparent.sh** this is the gui to make your life easier...

select your theme and panel that you want transparent and generate the new theme from the bottom of the window...

let me know how did it go...

**Comment by psifidotos** [comment]
@AndydeCleyre I think that maybe the fact that you used default instead of the theme's name could be the issue... From the gui just choose the theme by its name...

**Comment by AndydeCleyre** [comment]
The breeze theme is only available as "default"

**Comment by psifidotos** [comment]
Oh.... So this does not suceed for Breeze????? I use Breeze-Dark and it's ok....

**Comment by psifidotos** [comment]
in my system the Breeze theme is called.... breeze-light... I think that **default** is just a link for the current selected theme, so this is not always the Breeze one...

**Comment by psifidotos** [comment]
![image](https://cloud.githubusercontent.com/assets/2216474/18400923/a08d1ba4-76e0-11e6-85ee-112730a1eec5.png)

**Comment by AndydeCleyre** [comment]
breeze-light, breeze-dark, and breeze/default are 3 separate themes, differentiated by color. breeze-light was created to maintain the legacy colors when breeze (plain) transitioned to using colors from the user's kde theme.

**Comment by psifidotos** [comment]
![image](https://cloud.githubusercontent.com/assets/2216474/18401047/36624c3a-76e1-11e6-80a1-2e00ec33cd32.png)

Ohhhh!! I didnt know... Ok... default is working for me....

**Comment by psifidotos** [comment]
[default - West Transparent.tar.gz](https://github.com/psifidotos/nowdock-panel/files/464718/default.-.West.Transparent.tar.gz)

if you wanna test this also...

**Comment by AndydeCleyre** [comment]
If you'll forgive the jitter, [here's](https://streamable.com/qpar) what I tried. Sorry for hijacking this report; if I'm not doing anything obviously wrong I'll create a new one. I'm using both your panel and plasmoid.

Ok, I'll give that theme a try.

**Comment by psifidotos** [comment]
if you try another theme for testing reasons, the issue remains? 
maybe also a logout/login to update cache possibly...

**Comment by AndydeCleyre** [comment]
The one you sent functions the same as when I tried, as in the video, except it "ate" my breeze theme (breeze is no longer a choice until I delete your theme).

I just tested with Papirus, and it works as (I believe) intended. There's a major blur effect where the panel is, which I don't want, but in general that transparency works.

**Comment by kupiqu** [comment]
I have used default Breeze theme West adapted for long time (now on dark theme though) and didn't see any problem, try perhaps reloading plasmashell?

```
killall plasmashell
plasmashell &
```

In my case it didn't eat anything either, it just renames it as for other non-default themes.

Used  plasma transparent panel version 0.2.2

**Comment by psifidotos** [comment]
- for blurring the only thing you can do is to disable it from the kwin effects...

for the theme... that is strange...

I have to leave you for now... If you have any news, send us @AndydeCleyre

**Comment by psifidotos** [comment]
Ohhhh and about eating it... The script does not touch at all the original theme... It just creates a new theme based on the original one in folder:
**/home/<user>/.local/share/plasma/desktoptheme/**

**Comment by kupiqu** [comment]
I tried again with master github version and worked fine in my system. Sorry can't help more, can't reproduce your issue.

**Comment by AndydeCleyre** [comment]
@kupiqu Yeah I had tried that, and just tried a full reboot. No change.

**Comment by AndydeCleyre** [comment]
I'm using these versions:

| Package | Version |
| --- | --- |
| plasma-framework | 5.25.0 |
| plasma-{desktop,workspace | 5.7.4 |

**Comment by kupiqu** [comment]
I think your issue may be that you didn't disable blur in desktop effects, perhaps?

**Comment by kupiqu** [comment]
Oh wait, you don't have to do this anymore

**Comment by AndydeCleyre** [comment]
@kupiqu 

Ah! Thank you! Yes, that blur effect was causing the blur, but when looking at that I saw I had another effect half-enabled: Background contrast. Disabling that fixed the transparency!

Thanks everyone

**Comment by kupiqu** [comment]
Great it works for you now :)

**Comment by psifidotos** [comment]
Nice news!!! ;) have fun with it !!!

**Comment by AndydeCleyre** [comment]
Back to the right topic: I don't know what triggers it, but sometimes the icons get a lot tinier than they need to be.

**Comment by psifidotos** [comment]
@AndydeCleyre , the icon sizes make jumps from one state to another and **NOT** in between for example...

[16,22,32,48,64,92,128,256]

 the implementation if it needs to shrink from 64px.  it will go to 48px. and if it needs to grow it will go to 92px.

**Comment by psifidotos** [comment]
fixed in master and svgs branches
