### ISSUE TITLE
Asymmetric lateral margins when the panel anchor is set other than centered

### ISSUE THREAD

**Issue by kupiqu** [psifidotos/nowdock-panel#11]
This is a rather minor thing, but it would be nice to decrease the ending lateral margin that is opposite to the anchor, so the panel looks symmetric. Please see the attached screenshot.

<img width="33" alt="screenshot_20160909_090534" src="https://cloud.githubusercontent.com/assets/3875196/18387772/9e2ed204-766c-11e6-93ae-81813f5bac11.png">

I updated the screenshot so the effect is clearer (note that the effect is small and in the previous screenshot a bit difficult to see)

**Comment by psifidotos** [comment]
ohhhh ! You mean the the margin above "K" is smaller that the margin below the "Earth" icon?

**Comment by kupiqu** [comment]
Yep, an embarrassingly minor thing :)

**Comment by psifidotos** [comment]
actually ... For me... it isnt... :), it can be fixed easily I suppose and sometimes we look something and something doesnt fit... something so small dont catch the eye but many users would feel it... :-)

**Comment by kupiqu** [comment]
Nice, thanks!
