### ISSUE TITLE
Wrong launcher growing when mouse hover

### ISSUE THREAD

**Issue by alexjp** [psifidotos/nowdock-panel#13]
Hi,

I added one firefox launcher to the nowdock panel and a nowdock plasmoid with a firefox launcher in it.

See video -> https://youtu.be/O2uwhxJmPto , it shows the firefox launcher outside of nowdock not growing when mouse over, but growing when mouse over a launcher in nowdock.

Thanks !

**Comment by alexjp** [comment]
Video after plasmashell restart: -> https://youtu.be/jy4qOwPd2DQ

It behaves a little different

**Comment by psifidotos** [comment]
@alexjp as I see in your videos you have your desktop unlocked... please lock your widgets and tell me if it remains... The sure thing is that in unlocked state the firefox **plasmoid** shouldnt grow at all!!!

**Comment by alexjp** [comment]
>  please lock your widgets and tell me if it remains...

You are right, with locked state, issue seems fixed !

**Comment by psifidotos** [comment]
ok !
