### ISSUE TITLE
Move the nowdock panel settings button to the anchor's opposite location

### ISSUE THREAD

**Issue by kupiqu** [psifidotos/nowdock-panel#15]
Depending on settings, it is almost impossible to click on panel's settings button. Please see screenshot:

<img width="43" alt="screenshot_20160914_013816" src="https://cloud.githubusercontent.com/assets/3875196/18501093/f74029bc-7a1b-11e6-9400-2b75debf8c34.png">

Perhaps it would be even better to scale icons down when plasmashell is unlocked to leave space for the settings button, and then restore original size when desktop is locked again. This would be particularly good when the panel is full.

**Comment by psifidotos** [comment]
the button I think it should go on top (this is a visual bug)....
Its placement has been chosen to be opposite the plasma panel settings button... 
the icons size in unlocked state shows the maximum icon size based on the height (in horizontal case) of the panel...

**Comment by psifidotos** [comment]
fixed in **master** branch... now dock configuration button should be ontop now...
