### ISSUE TITLE
How to add Now Dock Panel?

### ISSUE THREAD

**Issue by thnt** [psifidotos/nowdock-panel#19]
Installed Now Dock Panel & Now Dock Plasmoid from `Add Widget` > `Download New Widget`
But Now Dock Panel not show in Add Panel menu
http://i.imgur.com/53nWDlu.png
Plasma 5.7.95 (5.8 beta)

**Comment by psifidotos** [comment]
I dont have a (5.8 beta) to test this but it should...
As soon as 5.8 gets out I will  see what is going on...
Lets ask and the others...

**Comment by psifidotos** [comment]
until then, you could also try to install it with the manual way in order to give us feedback if the problem remains...
1. download **master** branch of Now Dock Panel
2. just run **install-global.sh**

**Comment by thnt** [comment]
It still doesn't show in `Add Panel` menu.
Run `plasmapkg2 -l` i can see now dock was installed as plasmoid:

```
org.kde.store.nowdock.panel
org.kde.store.nowdock.plasmoid
```

I think the panel should be installed as a `layout-template`. Run `plasmapkg2 -t layout-template -l`, i can see current available panel templates:

```
org.kde.plasma.desktop.defaultPanel
org.kde.plasma.desktop.emptyPanel
org.opensuse.desktop.defaultPanel
```

**Comment by psifidotos** [comment]
Ok... :)

as it appears in Plasma 5.8 maybe also a layout is needed for empty panel... 
Some information.... In Plasma, panels are just plasmoids with a small different behavior...
So it is correct that you see:

`org.kde.store.nowdock.panel`

through **plasmapkg2 -l**

until Plasma 5.7 a layout for an empty panel was not needed, I dont know if in Plasma 5.8 this has changed...

We can try to install also a layout to see if this is fixed...

can you install the following layout **(Now Dock Default Panel)** with command ?
_(this adds a now dock plasmoid and a clock in a now dock panel)_

`plasmapkg2 -t layout-template -i`

[nowdock-panel-defaultlayout.zip](https://github.com/psifidotos/nowdock-panel/files/495854/nowdock-panel-defaultlayout.zip)

**Comment by psifidotos** [comment]
I also run in my **Plasma 5.7**

`plasmapkg2 -t layout-template -l`

and the following were appearing:

```
org.kde.plasma.desktop.defaultPanel
org.kdelook.nowdock.defaultPanel
```

the empty panels didnt need a layout with them...

more close to the fact that empty panels need an accompanied layout in **Plasma 5.8**...

**Comment by psifidotos** [comment]
this is the following response from Plasma developers...

> Ok, there was a change between 5.7 and 5.7.95  that broke this.
> It was then fixed between the beta and final because of this very  reason.
> 
> latest Plasma/5.8 branch (anything after 79000dab31d4da97f8031275f2cf66395af64fc9  - 20/09/2016)
> should be fine, as should the final release.

**Comment by arthurflor23** [comment]
Any chance to add Now Dock Panel in KDE 5.8, even if it manually?

Same problem here

**Comment by psifidotos** [comment]
two possibilities,
1. in a couple of days I will release 0.4 version for which you can use the install-local.sh script to install it on Plasma 5.8 **or**
2. you can download now the **master** branch which already supports it.

**install-local.sh** installs the panel correctly for the current user but without translations
**install-global.sh** installs the panel for all users **with translations** but it needs some dependencies to be met first in the system

**Comment by psifidotos** [comment]
v0.4 which is compatible with Plasma 5.8 was released....
