### ISSUE TITLE
Locale code name

### ISSUE THREAD

**Issue by Steinhagen** [psifidotos/nowdock-panel#20]
For consistency sake, the language locale code should probably be kept for each po file.
Romanian: ro_RO.po
Traditional Chinese: zh_TW.po
Greek: el_GR.po

**Comment by Steinhagen** [comment]
I've double check right now. It seems that the translation was right according to the metadata.
Also, as a mistake from my part, the romanian language should've been named: **ro.po**

**Comment by psifidotos** [comment]
for Greek :) it is definetely "el", the el_GR is not working in my system...
this is why I asked you if you have tested with your systems... 
this could also be for the chinese...

I suppose bug reports will be received and then I will rename them correctly...

**Comment by psifidotos** [comment]
ok, I renamed romanian... It should work now for you...
