### ISSUE TITLE
Wonky Panel... automatic icon size mechanism must be fixed...

### ISSUE THREAD

**Issue by psifidotos** [psifidotos/nowdock-panel#29]
Sometimes the panel becomes wonky... This is caused mostly because of the automatic icon resizing....

https://streamable.com/tpxs

**Comment by AndydeCleyre** [comment]
If I understand correctly that I can just `git pull`, `sh ./install-global.sh`, and restart `plasmashell` to upgrade, I'm still experiencing this with `v0.4.0-110-g8fe8eff`.

**Comment by psifidotos** [comment]
where did you find these numbers?
v0.4.0-110-g8fe8eff 

did you pull the master branch?

**Comment by psifidotos** [comment]
ok I found it... it should be ok...

Needs info:

1. What icon size have you set?
2. What Applets Alignment are u using?
3. What maximum size for the panel have you set, have you altered it or is it full?
4. When does it occur? What are your last choices before the problem arises?

**Comment by psifidotos** [comment]
I have one more idea for this... Had you installed Now Dock Panel with install-local.sh in the past?

**Comment by AndydeCleyre** [comment]
I pulled the master branch, and got those numbers by running `git describe` in the checkout directory. Today though, the vibration only occurs when widgets are unlocked.

Property|Value
------------|--------
Applets Size|Automatic
Applets Alignment|Center
Maximum Size|I don't know -- it seems maximized (right side of screen)

It was immediately after logging in before, but today only in unlocked mode.

Yes, I had installed it with `install-local.sh` in the past. Since then I went back to the checkout directory and ran `plasmapkg2 -r .` in an effort to uninstall it before installing via the global script.

I see master branch is updated, I'll update and see if anything changes.

Hmm, I don't know if I missed this before, but now `v0.4.0-117-g2ff42dc` is failing to install:

```
-- The C compiler identification is GNU 6.2.1
-- The CXX compiler identification is GNU 6.2.1
-- Check for working C compiler: /usr/bin/cc
-- Check for working C compiler: /usr/bin/cc -- works
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Detecting C compile features
-- Detecting C compile features - done
-- Check for working CXX compiler: /usr/bin/c++
-- Check for working CXX compiler: /usr/bin/c++ -- works
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Detecting CXX compile features
-- Detecting CXX compile features - done
-- Installing in the same prefix as Qt, adopting their path scheme.
-- Found KF5Plasma: /usr/lib64/cmake/KF5Plasma/KF5PlasmaConfig.cmake (found version "5.28.0") 
-- Found KF5PlasmaQuick: /usr/lib64/cmake/KF5PlasmaQuick/KF5PlasmaQuickConfig.cmake (found version "5.28.0") 
-- Found KF5WindowSystem: /usr/lib64/cmake/KF5WindowSystem/KF5WindowSystemConfig.cmake (found version "5.28.0") 
CMake Warning at /usr/share/cmake-3.6/Modules/CMakeFindDependencyMacro.cmake:65 (find_package):
  By not providing "FindKF5DesignerPlugin.cmake" in CMAKE_MODULE_PATH this
  project has asked CMake to find a package configuration file provided by
  "KF5DesignerPlugin", but CMake did not find one.

  Could not find a package configuration file provided by "KF5DesignerPlugin"
  (requested version 5.28.0) with any of the following names:

    KF5DesignerPluginConfig.cmake
    kf5designerplugin-config.cmake

  Add the installation prefix of "KF5DesignerPlugin" to CMAKE_PREFIX_PATH or
  set "KF5DesignerPlugin_DIR" to a directory containing one of the above
  files.  If "KF5DesignerPlugin" provides a separate development package or
  SDK, be sure it has been installed.
Call Stack (most recent call first):
  /usr/lib64/cmake/KF5KDELibs4Support/KF5KDELibs4SupportConfig.cmake:91 (find_dependency)
  /usr/share/ECM/find-modules/FindKF5.cmake:74 (find_package)
  libnowdock/CMakeLists.txt:6 (find_package)


CMake Warning at /usr/share/ECM/find-modules/FindKF5.cmake:74 (find_package):
  Found package configuration file:

    /usr/lib64/cmake/KF5KDELibs4Support/KF5KDELibs4SupportConfig.cmake

  but it set KF5KDELibs4Support_FOUND to FALSE so package
  "KF5KDELibs4Support" is considered to be NOT FOUND.  Reason given by
  package:

  KF5KDELibs4Support could not be found because dependency KF5DesignerPlugin
  could not be found.

Call Stack (most recent call first):
  libnowdock/CMakeLists.txt:6 (find_package)


-- Could NOT find KF5KDELibs4Support (found version "5.28.0"), checked the following files:
    /usr/lib64/cmake/KF5KDELibs4Support/KF5KDELibs4SupportConfig.cmake (version 5.28.0)
    Reason given by package: KF5KDELibs4Support could not be found because dependency KF5DesignerPlugin could not be found.

-- Found KF5CoreAddons: /usr/lib64/cmake/KF5CoreAddons/KF5CoreAddonsConfig.cmake (found version "5.28.0") 
CMake Error at /usr/share/cmake-3.6/Modules/FindPackageHandleStandardArgs.cmake:148 (message):
  Could NOT find KF5 (missing: KDELibs4Support) (found version "5.28.0")
Call Stack (most recent call first):
  /usr/share/cmake-3.6/Modules/FindPackageHandleStandardArgs.cmake:388 (_FPHSA_FAILURE_MESSAGE)
  /usr/share/ECM/find-modules/FindKF5.cmake:110 (find_package_handle_standard_args)
  libnowdock/CMakeLists.txt:6 (find_package)


-- Configuring incomplete, errors occurred!
```

**Comment by psifidotos** [comment]
> Applets Size: Automatic

there is no Automatic any more in new versions... This means that is hasnt uninstalled correctly the previous version... Try to run the **uninstall-local.sh** script, I believe it will remove correctly your local version.... One way to be sure is that in the Now Dock Panel Configuration window there is at the **top-right** corner a version number, it should be **0.4.90**

>   KF5KDELibs4Support could not be found because dependency KF5DesignerPlugin
  could not be found.

this is your system issue or your distribution, you should have installed at your system your developement packages for **KDE Frameworks**, especially based on the error, **kdelibs4support** and **kdesignerplugin** both belong to **KDE Frameworks**

**Comment by AndydeCleyre** [comment]
Thank you, I hadn't noticed those uninstall scripts. While I already had kdelibs4support installed, I installed kdesignerplugin and it installed successfully. The issue seems to be resolved!

**Comment by psifidotos** [comment]
:+1: 

we 'll leave a few days more this bug open in case it reappears...

**Comment by psifidotos** [comment]
One more thing: Can you send also your distro, plasma version and frameworks version? There are users that **can not** install the new version and I am trying to find out the reason...

thanks a lot...

**Comment by AndydeCleyre** [comment]
Arch Linux
plasma-desktop 5.8.4
plasma-framework 5.28.0

**Comment by psifidotos** [comment]
:+1:

**Comment by psifidotos** [comment]
@AndydeCleyre and one more thing, if you please... Can you add a new Now Dock Panel in your system?

**Comment by AndydeCleyre** [comment]
I'm at a different (but extremely similar) system now, and see that in order to build both packages I also need the package `extra-cmake-modules`.

So on this system I uninstalled everything, installed everything, and added two Now Dock panels. Is that what you wanted me to test? The second one does not show any of the plasmoid items when widgets are locked.

As an aside, if there's no particular reason for the 128 px maximum on applet size, please bump it up some time.

**Comment by psifidotos** [comment]
> I'm at a different (but extremely similar) system now, and see that in order to build both packages I also need the package extra-cmake-modules.
> So on this system I uninstalled everything, installed everything, and added two Now Dock panels. Is that what you wanted me to test?

yes...

> The second one does not show any of the plasmoid items when widgets are locked.

 are you using "Auto-Hide" for plasma panel's setting?

> As an aside, if there's no particular reason for the 128 px maximum on applet size, please bump it up some time.

how much? you need more?

**Comment by AndydeCleyre** [comment]
I don't know, it was just the default settings for a new now dock panel.

I don't know exactly how big the icons should be, I'd just like to be able to fill the vertical space with 7-8 icons on the right side of the screen, at 1080p.

This bug has still not reappeared for me, btw. Thanks!

**Comment by psifidotos** [comment]
:+1:
