### ISSUE TITLE
Do not limit panel background size to >= 6 px

### ISSUE THREAD

**Issue by kupiqu** [psifidotos/nowdock-panel#3]
With my resolution best results are achieved for 4 px, so dots are centered in the panel, and the panel remains minimalistic.

I used to use this option in the plasmoid, which didn't have the limitation. This is now grayed out in the plasmoid as the setting is better in the panel. But to achieve now the same behavior I had before, I needed to edit it manually in the settings of plasma desktop, which is a bit painful for an average user.

**Comment by psifidotos** [comment]
this must be fixed... you are right...

**Comment by psifidotos** [comment]
fixed in **master** and improve the way the user can do small adjustments...
