### ISSUE TITLE
Right click on systray icons with nowdock panel

### ISSUE THREAD

**Issue by alexjp** [psifidotos/nowdock-panel#34]
Hi,

Don't know why, but when I have the systray on nowdock panel and desktop locked, I can't open the right click context menu on the systray icons.

When the desktop widgets is unlocked, right click menu context appears fine.

Thanks !

**Comment by psifidotos** [comment]
this is more difficult than it sounds... With workarounds I can make it work for systray in order to show the menu for the applets inside the systray but not for the systray itself if the widgets arent unlocked...

**Comment by psifidotos** [comment]
@alexjp I hope this works for you also...

**Comment by alexjp** [comment]
> @alexjp I hope this works for you also...

Yep ... just updated to latest code!

You are sincerely awesome !

**Comment by psifidotos** [comment]
:+1:
