### ISSUE TITLE
a new dock can not be added...

### ISSUE THREAD

**Issue by psifidotos** [psifidotos/nowdock-panel#37]
the json metadata broke probably the panel addition....

**Comment by jsmitar** [comment]
Ok: I restart plasma shell, but is impossible add a new dock

**Comment by psifidotos** [comment]
@audoban what distribution are you using? is plasma installed in a different path than /usr ?

**Comment by jsmitar** [comment]
I'm using openSUSE 42.1, and plasma is installed into /usr.
Also I using plasma from repositories of [KDE](https://build.opensuse.org/project/subprojects/KDE)

**Comment by psifidotos** [comment]
We have exactly the same system instead that I have updated to Plasma 5.8.4

**Comment by psifidotos** [comment]
My KDE repos are:

Frameworks & Plasma: http://download.opensuse.org/repositories/KDE:/Frameworks5/openSUSE_Leap_42.1

Qt5:
http://download.opensuse.org/repositories/KDE:/Qt5/openSUSE_Leap_42.1/

**Comment by psifidotos** [comment]
@audoban does this still persists? is it possible to update to Plasma 5.8.4?

Most of the users are using as  a combination (Plasma 5.8.4 - Frameworks 5.28.0) and they dont have any issues...

**Comment by jsmitar** [comment]
ok, I will update at night

**Comment by psifidotos** [comment]
:+1:

**Comment by jsmitar** [comment]
ok. Now I can add new docks.

**Comment by jsmitar** [comment]
ok. Now I can add a new dock.

**Comment by psifidotos** [comment]
:+1:  this is good...
