### ISSUE TITLE
Glitching icons and double bar

### ISSUE THREAD

**Issue by rbo3djej** [psifidotos/nowdock-panel#41]
Hi, 
I am using the latest version of both plasma and nowdock-panel and when i move the mouse in the dock the icons keep switching and i seem to have double bars i guess one is of the nowdock-panel and the other one is from plasma? Is it possible to only keep one ? 
https://u.teknik.io/AIzn7.mkv Video showing the two bugs

**Comment by psifidotos** [comment]
The link is not working...

Στις 15 Δεκ 2016 11:19, ο χρήστης "rbo3djej" <notifications@github.com>
έγραψε:

**Comment by psifidotos** [comment]
Ok... Ok saw it... Try to usr another icon size, eg 64 and another icon
there, eg the default breeze, and send my what is happening...

What do you mean by "double bar"?

Στις 15 Δεκ 2016 13:28, ο χρήστης "Michail Vourlakos" <mvourlakos@gmail.com>
έγραψε:

**Comment by psifidotos** [comment]
another icon theme ...

Στις 15 Δεκ 2016 13:36, ο χρήστης "Michail Vourlakos" <mvourlakos@gmail.com>
έγραψε:

**Comment by rbo3djej** [comment]
i changed the icon theme and it's fixed now and for the double bar i mean that i have 2 panels showing up ![2 panels](https://cloud.githubusercontent.com/assets/24584935/21223882/cb3d35de-c2c9-11e6-914b-7e3953b659eb.png) and even with auto hide on sometimes one of the panels will stay like this 
![picture](https://cloud.githubusercontent.com/assets/24584935/21223883/cb3e21b0-c2c9-11e6-840c-7f36c7c16301.png)

**Comment by psifidotos** [comment]
this is happening because you need the transparent panel script in order to provide you transparency for that specific panel (based on the panels position). You can use: https://dl.opendesktop.org/api/files/download/id/1481722071/plasma-transparent-panel.py.v0.2.2.tar.gz in order to produce for you this theme... In Plasma 5.9 this step wont be needed...

**Comment by rbo3djej** [comment]
Thank for help 👍
