### ISSUE TITLE
nowdockpanel installation issue in openSUSE tumbleweed

### ISSUE THREAD

**Issue by JenaPlinsky** [psifidotos/nowdock-panel#42]
Hi psifidotos'm trying to install your fantastic plasmoiid but I get these errors. Do you know tell me where I'm wrong?

Plasma 5.8.90
Versione Qt: 5.7.1
KDE Frameworks 5.30.0

########## UNINSTALL ##########

> 

`Ivan@UltrabookSamsung:~/Scaricati/nowdock-panel-source-v0.5.0> ./uninstall-local.sh     
Calling KPluginInfo::property("X-KDE-PluginInfo-Name") is deprecated, use KPluginInfo::pluginName() in "/usr/lib64/qt5/plugins/plasma/packagestructure/plasma_packagestructure_share.so" instead.
kf5.kcoreaddons.desktopparser: Could not locate service type file kservicetypes5/plasma-popupapplet.desktop, tried ("/home/Ivan/.local/share", "/usr/share")
kf5.kcoreaddons.desktopparser: Could not locate service type file kservicetypes5/plasma-popupapplet.desktop, tried ("/home/Ivan/.local/share", "/usr/share")
kf5.kcoreaddons.desktopparser: Could not locate service type file kservicetypes5/plasma-popupapplet.desktop, tried ("/home/Ivan/.local/share", "/usr/share")
kf5.kcoreaddons.desktopparser: Could not locate service type file kservicetypes5/plasma-popupapplet.desktop, tried ("/home/Ivan/.local/share", "/usr/share")
kf5.kcoreaddons.desktopparser: Could not locate service type file kservicetypes5/plasma-popupapplet.desktop, tried ("/home/Ivan/.local/share", "/usr/share")
kf5.kcoreaddons.desktopparser: Could not locate service type file kservicetypes5/plasma-popupapplet.desktop, tried ("/home/Ivan/.local/share", "/usr/share")
kf5.kcoreaddons.desktopparser: Could not locate service type file kservicetypes5/plasma-popupapplet.desktop, tried ("/home/Ivan/.local/share", "/usr/share")
kf5.kcoreaddons.desktopparser: Could not locate service type file kservicetypes5/plasma-popupapplet.desktop, tried ("/home/Ivan/.local/share", "/usr/share")
kf5.kcoreaddons.desktopparser: Could not locate service type file kservicetypes5/plasma-popupapplet.desktop, tried ("/home/Ivan/.local/share", "/usr/share")
kf5.kcoreaddons.desktopparser: Could not locate service type file kservicetypes5/plasma-popupapplet.desktop, tried ("/home/Ivan/.local/share", "/usr/share")
kf5.kcoreaddons.desktopparser: Could not locate service type file kservicetypes5/plasma-popupapplet.desktop, tried ("/home/Ivan/.local/share", "/usr/share")
kf5.kcoreaddons.desktopparser: Could not locate service type file kservicetypes5/plasma-popupapplet.desktop, tried ("/home/Ivan/.local/share", "/usr/share")
kf5.kcoreaddons.desktopparser: Could not locate service type file kservicetypes5/plasma-popupapplet.desktop, tried ("/home/Ivan/.local/share", "/usr/share")
kf5.kcoreaddons.desktopparser: Could not locate service type file kservicetypes5/plasma-popupapplet.desktop, tried ("/home/Ivan/.local/share", "/usr/share")
kf5.kcoreaddons.desktopparser: Could not locate service type file kservicetypes5/plasma-popupapplet.desktop, tried ("/home/Ivan/.local/share", "/usr/share")
Calling KPluginInfo::property("X-KDE-PluginInfo-Name") is deprecated, use KPluginInfo::pluginName() in "/usr/lib64/qt5/plugins/plasma/packagestructure/plasma_packagestructure_share.so" instead.
Errore: l'estensione  non Ã¨ installata.
Calling KPluginInfo::property("X-KDE-PluginInfo-Name") is deprecated, use KPluginInfo::pluginName() in "/usr/lib64/qt5/plugins/plasma/packagestructure/plasma_packagestructure_share.so" instead.
kf5.kcoreaddons.desktopparser: Could not locate service type file kservicetypes5/plasma-popupapplet.desktop, tried ("/home/Ivan/.local/share", "/usr/share")
kf5.kcoreaddons.desktopparser: Could not locate service type file kservicetypes5/plasma-popupapplet.desktop, tried ("/home/Ivan/.local/share", "/usr/share")
kf5.kcoreaddons.desktopparser: Could not locate service type file kservicetypes5/plasma-popupapplet.desktop, tried ("/home/Ivan/.local/share", "/usr/share")
kf5.kcoreaddons.desktopparser: Could not locate service type file kservicetypes5/plasma-popupapplet.desktop, tried ("/home/Ivan/.local/share", "/usr/share")
kf5.kcoreaddons.desktopparser: Could not locate service type file kservicetypes5/plasma-popupapplet.desktop, tried ("/home/Ivan/.local/share", "/usr/share")
kf5.kcoreaddons.desktopparser: Could not locate service type file kservicetypes5/plasma-popupapplet.desktop, tried ("/home/Ivan/.local/share", "/usr/share")
kf5.kcoreaddons.desktopparser: Could not locate service type file kservicetypes5/plasma-popupapplet.desktop, tried ("/home/Ivan/.local/share", "/usr/share")
kf5.kcoreaddons.desktopparser: Could not locate service type file kservicetypes5/plasma-popupapplet.desktop, tried ("/home/Ivan/.local/share", "/usr/share")
kf5.kcoreaddons.desktopparser: Could not locate service type file kservicetypes5/plasma-popupapplet.desktop, tried ("/home/Ivan/.local/share", "/usr/share")
kf5.kcoreaddons.desktopparser: Could not locate service type file kservicetypes5/plasma-popupapplet.desktop, tried ("/home/Ivan/.local/share", "/usr/share")
kf5.kcoreaddons.desktopparser: Could not locate service type file kservicetypes5/plasma-popupapplet.desktop, tried ("/home/Ivan/.local/share", "/usr/share")
kf5.kcoreaddons.desktopparser: Could not locate service type file kservicetypes5/plasma-popupapplet.desktop, tried ("/home/Ivan/.local/share", "/usr/share")
kf5.kcoreaddons.desktopparser: Could not locate service type file kservicetypes5/plasma-popupapplet.desktop, tried ("/home/Ivan/.local/share", "/usr/share")
kf5.kcoreaddons.desktopparser: Could not locate service type file kservicetypes5/plasma-popupapplet.desktop, tried ("/home/Ivan/.local/share", "/usr/share")
kf5.kcoreaddons.desktopparser: Could not locate service type file kservicetypes5/plasma-popupapplet.desktop, tried ("/home/Ivan/.local/share", "/usr/share")
Calling KPluginInfo::property("X-KDE-PluginInfo-Name") is deprecated, use KPluginInfo::pluginName() in "/usr/lib64/qt5/plugins/plasma/packagestructure/plasma_packagestructure_share.so" instead.
Errore: l'estensione  non Ã¨ installata.
kf5.kcoreaddons.desktopparser: Could not locate service type file kservicetypes5/plasma-layouttemplate.desktop, tried ("/home/Ivan/.local/share", "/usr/share")
kf5.kcoreaddons.desktopparser: Could not locate service type file kservicetypes5/plasma-layouttemplate.desktop, tried ("/home/Ivan/.local/share", "/usr/share")
Errore: l'estensione  non Ã¨ installata.
kf5.kcoreaddons.desktopparser: Could not locate service type file kservicetypes5/plasma-layouttemplate.desktop, tried ("/home/Ivan/.local/share", "/usr/share")
kf5.kcoreaddons.desktopparser: Could not locate service type file kservicetypes5/plasma-layouttemplate.desktop, tried ("/home/Ivan/.local/share", "/usr/share")
Errore: l'estensione  non Ã¨ installata.
Ivan@UltrabookSamsung:~/Scaricati/nowdock-panel-source-v0.5.0> 
`

########## INSTALL ##########
`Ivan@UltrabookSamsung:~/Scaricati/nowdock-panel-source-v0.5.0> sudo ./install-global.sh      
[sudo] password di root: 

-- The C compiler identification is GNU 6.2.1
-- The CXX compiler identification is GNU 6.2.1
-- Check for working C compiler: /usr/bin/cc
-- Check for working C compiler: /usr/bin/cc -- works
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Detecting C compile features
-- Detecting C compile features - done
-- Check for working CXX compiler: /usr/bin/c++
-- Check for working CXX compiler: /usr/bin/c++ -- works
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Detecting CXX compile features
-- Detecting CXX compile features - done
CMake Warning at CMakeLists.txt:14 (find_package):
  By not providing "FindKF5Plasma.cmake" in CMAKE_MODULE_PATH this project
  has asked CMake to find a package configuration file provided by
  "KF5Plasma", but CMake did not find one.

  Could not find a package configuration file provided by "KF5Plasma" with
  any of the following names:

    KF5PlasmaConfig.cmake
    kf5plasma-config.cmake

  Add the installation prefix of "KF5Plasma" to CMAKE_PREFIX_PATH or set
  "KF5Plasma_DIR" to a directory containing one of the above files.  If
  "KF5Plasma" provides a separate development package or SDK, be sure it has
  been installed.

CMake Warning at /usr/share/ECM/find-modules/FindKF5.cmake:74 (find_package):
  Could not find a package configuration file provided by "KF5Plasma" with
  any of the following names:

    KF5PlasmaConfig.cmake
    kf5plasma-config.cmake

  Add the installation prefix of "KF5Plasma" to CMAKE_PREFIX_PATH or set
  "KF5Plasma_DIR" to a directory containing one of the above files.  If
  "KF5Plasma" provides a separate development package or SDK, be sure it has
  been installed.
Call Stack (most recent call first):
  libnowdock/CMakeLists.txt:6 (find_package)

-- Could NOT find KF5Plasma: found neither KF5PlasmaConfig.cmake nor kf5plasma-config.cmake 
CMake Warning at /usr/share/ECM/find-modules/FindKF5.cmake:74 (find_package):
  Could not find a package configuration file provided by "KF5PlasmaQuick"
  with any of the following names:

    KF5PlasmaQuickConfig.cmake
    kf5plasmaquick-config.cmake

  Add the installation prefix of "KF5PlasmaQuick" to CMAKE_PREFIX_PATH or set
  "KF5PlasmaQuick_DIR" to a directory containing one of the above files.  If
  "KF5PlasmaQuick" provides a separate development package or SDK, be sure it
  has been installed.
Call Stack (most recent call first):
  libnowdock/CMakeLists.txt:6 (find_package)

-- Could NOT find KF5PlasmaQuick: found neither KF5PlasmaQuickConfig.cmake nor kf5plasmaquick-config.cmake 
CMake Warning at /usr/share/ECM/find-modules/FindKF5.cmake:74 (find_package):
  Could not find a package configuration file provided by "KF5WindowSystem"
  with any of the following names:

    KF5WindowSystemConfig.cmake
    kf5windowsystem-config.cmake

  Add the installation prefix of "KF5WindowSystem" to CMAKE_PREFIX_PATH or
  set "KF5WindowSystem_DIR" to a directory containing one of the above files.
  If "KF5WindowSystem" provides a separate development package or SDK, be
  sure it has been installed.
Call Stack (most recent call first):
  libnowdock/CMakeLists.txt:6 (find_package)

-- Could NOT find KF5WindowSystem: found neither KF5WindowSystemConfig.cmake nor kf5windowsystem-config.cmake 
CMake Warning at /usr/share/ECM/find-modules/FindKF5.cmake:74 (find_package):
  Could not find a package configuration file provided by
  "KF5KDELibs4Support" with any of the following names:

    KF5KDELibs4SupportConfig.cmake
    kf5kdelibs4support-config.cmake

  Add the installation prefix of "KF5KDELibs4Support" to CMAKE_PREFIX_PATH or
  set "KF5KDELibs4Support_DIR" to a directory containing one of the above
  files.  If "KF5KDELibs4Support" provides a separate development package or
  SDK, be sure it has been installed.
Call Stack (most recent call first):
  libnowdock/CMakeLists.txt:6 (find_package)

-- Could NOT find KF5KDELibs4Support: found neither KF5KDELibs4SupportConfig.cmake nor kf5kdelibs4support-config.cmake 
CMake Warning at /usr/share/ECM/find-modules/FindKF5.cmake:74 (find_package):
  Could not find a package configuration file provided by "KF5CoreAddons"
  with any of the following names:

    KF5CoreAddonsConfig.cmake
    kf5coreaddons-config.cmake

  Add the installation prefix of "KF5CoreAddons" to CMAKE_PREFIX_PATH or set
  "KF5CoreAddons_DIR" to a directory containing one of the above files.  If
  "KF5CoreAddons" provides a separate development package or SDK, be sure it
  has been installed.
Call Stack (most recent call first):
  libnowdock/CMakeLists.txt:6 (find_package)

-- Could NOT find KF5CoreAddons: found neither KF5CoreAddonsConfig.cmake nor kf5coreaddons-config.cmake 
CMake Error at /usr/share/cmake/Modules/FindPackageHandleStandardArgs.cmake:138 (message):
  Could NOT find KF5 (missing: Plasma PlasmaQuick WindowSystem
  KDELibs4Support CoreAddons)
Call Stack (most recent call first):
  /usr/share/cmake/Modules/FindPackageHandleStandardArgs.cmake:378 (_FPHSA_FAILURE_MESSAGE)
  /usr/share/ECM/find-modules/FindKF5.cmake:110 (find_package_handle_standard_args)
  libnowdock/CMakeLists.txt:6 (find_package)

-- Configuring incomplete, errors occurred!
See also "/home/Ivan/Scaricati/nowdock-panel-source-v0.5.0/build/CMakeFiles/CMakeOutput.log".`

**Comment by psifidotos** [comment]
Hello @JenaPlinsky ,

if you were using the official Tumbleweed versions you could use directly:
https://software.opensuse.org/package/plasma5-panel-nowdock?search_term=now+dock

I am also using openSUSE, so I have packaged it for Tumbleweed and Leap...

but I think you are using the bleeding edge versions... :)
from you configuration you are missing the development packages for the libraries, you must install:

- plasma-framework-devel
- kdeclarative-devel
- kwindowsystem-devel
- kdelibs4support-devel
- kcoreaddons-devel

I think these will be sufficient...

**Comment by JenaPlinsky** [comment]
Ok thanks solved !!! installation goes fine, with its dev dependences

**Comment by psifidotos** [comment]
Nice to hear!!!
