### ISSUE TITLE
Shadows

### ISSUE THREAD

**Issue by JenaPlinsky** [psifidotos/nowdock-panel#46]
174/5000
There are two controls for enabling shadows, well, I have the impression that if both are active, their shadows overlap, worsening the visual quality

**Comment by psifidotos** [comment]
Is it possible to send some zoomed
 screenshots to compare?

Στις 16 Δεκ 2016 2:15 π.μ., ο χρήστης "JenaPlinsky" <
notifications@github.com> έγραψε:

**Comment by JenaPlinsky** [comment]
Solved :) it was my mistake I confused the native icon shadow ...I thought it had been created by an 
algorithm and after having enabled the shadows on nowdock I was looked like a double effect ... so excuse me : )

It makes sense to have a shadow option for applets and another for apps icons ?

**Comment by psifidotos** [comment]
:+1: 

There is discussion for settings if you want to contribute: https://github.com/psifidotos/nowdock-panel/issues/49

I think that two different shadows options(one for plasmoid and one for panel) do not make sense at all... Piece by piece I think the settings must be combined in one place...

**Comment by JenaPlinsky** [comment]
O Yeah I am imagined ....work in progress ;)
Really compliments  You are doing a fantastic job !!!

**Comment by psifidotos** [comment]
thank u !! :)
