### ISSUE TITLE
Panel does not occupy minimal size

### ISSUE THREAD

**Issue by rokups** [psifidotos/nowdock-panel#48]
When editing panel we have two sets of handles that define min and max panel sizes. Panel should shrink to minimal size that is available but leave enough space for widgets. Currently it always occupies max size. For clarity i uploaded image noting handles and where where should be actual panel end (white strip).

![example](https://cloud.githubusercontent.com/assets/19151258/21256595/2065af04-c36b-11e6-8128-7fd506673c46.png)

**Comment by psifidotos** [comment]
I dont quite understand what you what to achieve... In you screenshot what
do you what as behavior?

Στις 16 Δεκ 2016 10:41 π.μ., ο χρήστης "Rokas Kupstys" <
notifications@github.com> έγραψε:

**Comment by psifidotos** [comment]
What do you want as behavior...

Στις 16 Δεκ 2016 11:46 π.μ., ο χρήστης "Michail Vourlakos" <
mvourlakos@gmail.com> έγραψε:

**Comment by rokups** [comment]
Actually this was me trying to get plasma panel to behave like panel background. After disabling desktop effects and enabling panel background it all works as expected. Sorry for the noise again ;)

**Comment by psifidotos** [comment]
no worries...

Στις 16 Δεκ 2016 12:02 μ.μ., ο χρήστης "Rokas Kupstys" <
notifications@github.com> έγραψε:
