### ISSUE TITLE
Semantics

### ISSUE THREAD

**Issue by JenaPlinsky** [psifidotos/nowdock-panel#51]
is possible have different launcher set by activities
 ex.
   dev launchers
           kdevelop
           kate
   graphics launcers
           Gimp
           wine Photoshop
   Office
           Sheet
           LibreOffice
           wine Excel

If I instalall from master branch, us there a way to preserve the settings saved in the plasma-org.kde.plasma.desktop-appletsrc?

**Comment by psifidotos** [comment]
this is already supported... you can right click at a launcher... launchers can be in all activities or just spesific ones...

**Comment by JenaPlinsky** [comment]
wowww
