### ISSUE TITLE
Could not find a package configuration file provided by "ECM"

### ISSUE THREAD

**Issue by vfiset** [psifidotos/nowdock-panel#57]
in version 0.5 (and master) when running install-global.sh, I get the following message.

I am running a vanilla manjaro 16.10

I am new to the arch world and also new to kde and I am a bit lost...

```
CMake Error at CMakeLists.txt:10 (find_package):
  Could not find a package configuration file provided by "ECM" (requested
  version 0.0.11) with any of the following names:

    ECMConfig.cmake
    ecm-config.cmake

  Add the installation prefix of "ECM" to CMAKE_PREFIX_PATH or set "ECM_DIR"
  to a directory containing one of the above files.  If "ECM" provides a
  separate development package or SDK, be sure it has been installed.
```

**Comment by psifidotos** [comment]
You could try first a pre-built package, from AUR:
https://aur.archlinux.org/packages/nowdock-panel

**Comment by vfiset** [comment]
thank you very much. The dock is awesome. A must have IMO. Cheers

**Comment by psifidotos** [comment]
thank u !!!

:+1:
