### ISSUE TITLE
Clicking Lock/Logout widget does nothing

### ISSUE THREAD

**Issue by rokups** [psifidotos/nowdock-panel#58]
As title says clicking does not trigger button action. Upon click button is briefly animated (highlighted).

**Comment by psifidotos** [comment]
you could try to lock it in order to not animate itself on hovering... afterwards it works as expected...

**Comment by rokups** [comment]
How is that done? I do not see any option anywhere that would allow "locking" separate widget.

**Comment by psifidotos** [comment]
unlock your widgets and after that for each widget in the  NowDock a locker appears

**Comment by rokups** [comment]
Oh, did not notice that. Thank you! This probably still should work from the start though.

**Comment by psifidotos** [comment]
Now Dock never promised that will work with any plasmoid implementation there is out there...
