### ISSUE TITLE
"Below Active" state for the panel

### ISSUE THREAD

**Issue by psifidotos** [psifidotos/nowdock-panel#6]
The panel should be able to support these two states .... This is of course something for kwin internals...

**Comment by psifidotos** [comment]
[bugs.kde.org link](https://bugs.kde.org/show_bug.cgi?id=368385)

**Comment by psifidotos** [comment]
https://github.com/psifidotos/nowdock-plasmoid/issues/58

**Comment by psifidotos** [comment]
and many more... :-) in master ....

https://github.com/psifidotos/nowdock-plasmoid/issues/58

**Comment by AndydeCleyre** [comment]
I believe the behavior here should be that it stays below the active window *until and unless* the cursor "wakes" it by hitting the edge of the screen, at which point it should display over the active window (until and unless the cursor leaves the panel area).

Presently, in this mode, it cannot be woken/raised when the active window is along the panel's screen edge (or maximized).

EDIT: Oh, it seems that *is* the behavior. I was experiencing as described above when using an external monitor. For now, ignore me. If I can reproduce later I'll open a new issue.

**Comment by psifidotos** [comment]
> Presently, in this mode, it cannot be woken/raised when the active window is along the panel's screen edge (or maximized).

I can reproduce this only when the active or fullscreen window has been set "Above All", in that case the dock can not go above it...

> I was experiencing as described above when using an external monitor...

how things work with an external(secondary) monitor? I dont have one to test it... I implemented the code in order to respect these situations but I it could be possible that something does not work correctly...

**Comment by AndydeCleyre** [comment]
The case was an external primary monitor, with the built-in monitor disabled (so only 1 active). But it could have been bad luck; I'll try to reproduce tomorrow.

**Comment by psifidotos** [comment]
ok !!! :) there is also the chance that Now Dock didnt recognize that it changed screen...

**Comment by AndydeCleyre** [comment]
I was not able to reproduce the issue. This is working great for me.

**Comment by psifidotos** [comment]
:+1:
