### ISSUE TITLE
Icon size not permanent, goes back to small as possible

### ISSUE THREAD

**Issue by Wynnan** [psifidotos/nowdock-panel#63]
I'm new and just started using KDE Plasma so maybe it's just me messing something up, but I can't set the icon's size, because when I block the panel, the icons turn back to as small as possible.
![spectacle xj2277](https://cloud.githubusercontent.com/assets/24706999/21411207/ef79035c-c7e6-11e6-9964-a82d9e4cf9f4.png)
![spectacle vc2277](https://cloud.githubusercontent.com/assets/24706999/21411216/01efad92-c7e7-11e6-9d18-e2b8a5bd62cf.png)
![spectacle gv2277](https://cloud.githubusercontent.com/assets/24706999/21411223/11fe283a-c7e7-11e6-9b9d-4cfdeb7001b0.png)

**Comment by psifidotos** [comment]
Possible something with the maximum length that is set... Try to click at
three lines at the right side and try to alter maximum and minimum
length... You could try to maximize them...

Στις 22 Δεκ 2016 02:37, ο χρήστης "Wynnan" <notifications@github.com>
έγραψε:

**Comment by Wynnan** [comment]
Ok yeah, it was totally my bad, I'm sorry. Love it!
