### ISSUE TITLE
Is it possible for NowDock to "reserve" space, so maximized windows dont't cover it?

### ISSUE THREAD

**Issue by Petross404** [psifidotos/nowdock-panel#65]
Hello Psifidotos and well done for NowDock. As user of Cairo Dock, I have seen the customizability that the last provides and I thought you would like to hear some feedback on possible enhancements.

So, could it be possible for NowDock to provide an option to enable this feature? It is a really helpfull (and nice) dock and it is a pitty that someone can't access it, unless the windows are de-maximized.

**Comment by psifidotos** [comment]
> So, could it be possible for NowDock to provide an option to enable this feature? It is a really helpfull (and nice) dock and it is a pitty that someone can't access it, unless the windows are de-maximized.

this is only if the user has added only the Now Dock plasmoid in the desktop and not the Now Dock Panel....  Right click on your Desktop -> Add Panels -> Now Dock Default Panel
