### ISSUE TITLE
Is it possible for NowDock to give a user the ability to add a custom launcher?

### ISSUE THREAD

**Issue by Petross404** [psifidotos/nowdock-panel#66]
Another great feature would be the addittion of custom, user-defined launchers.

Let's say I want to add a launcher with another icon, or specify exactly which command and parameters it should execute if clicked.

Thank you anyway! NowDock is neat ;)

**Comment by psifidotos** [comment]
in Now Dock the user can add any plasmoids wants... The user just has to drag the launcher in the Now Dock Panel, left or right to the tasks... This is possible only for the **Now Dock Panel** not the plasmoid

**Comment by Petross404** [comment]
I see, thank you for your clarification. Now Dock Panel doesn't exist in 'Get new widgets', so I had only the plasmoid installed.

**Comment by Petross404** [comment]
https://github.com/Petross404/local/tree/master/kde-misc/nowdock-panel

I wrote an ebuild for the panel in order to properly install via Package Manager in Gentoo. If someone wants to improve it, or port it in some overlay he/she may do so.

**Comment by psifidotos** [comment]
nice ! :)

Latte Dock will solve many issues from eassiness point view....
https://github.com/psifidotos/Latte-Dock
