### ISSUE TITLE
NowDock Always Visible Option

### ISSUE THREAD

**Issue by chaoticmaster** [psifidotos/nowdock-panel#67]
I am trying to get the NowDock to always be visible and stop maximized windows from going below. It works if I set the Applets Visiblity to Always Visible and the Panel Settings to Always Visible. But when I lock widgets the Applets goes above the panel. Is there anyway to achieve the look and lock my widgets?

![locked widgets](https://cloud.githubusercontent.com/assets/22383251/22407482/18d76560-e635-11e6-8728-66eafc602493.png)
![unlocked widgets](https://cloud.githubusercontent.com/assets/22383251/22407483/18d8854e-e635-11e6-8876-71192ae7b37e.png)

**Comment by psifidotos** [comment]
Unfortunately i cant remember how this was achieved... you could try our new project Latte Dock for which this works correctly and easy

**Comment by chaoticmaster** [comment]
Thanks. Worked perfectly.
