### ISSUE TITLE
Panel size/height

### ISSUE THREAD

**Issue by SteveKej** [psifidotos/nowdock-panel#8]
I've noticed that the "show a red line" to determine the panel size isn't present in the settings moved from the nowdock plasmoid.  I'm wondering though, if it would be possible to set the optimum panel size automagically by calculating it from the icon size and the size needed for the corresponding animation.

**Comment by psifidotos** [comment]
reported: https://bugs.kde.org/show_bug.cgi?id=368488

---

This was something I was hoping the Now Dock Panel would solve... But unfortunately current plasma panel implementation does not support this. Current plasma implementation takes into account only the user configuration for this... I will create a feature request in the day, I hope only that the developers will agrree to add an overriding mechanism... This is also related with: #4 
- Concerning the red line I had in my mind that probably it is not used... Would you find it usefule to add it also in the Now Dock Panel?

**Comment by SteveKej** [comment]
Ok I see.  Thanks.  Personally I found the red line useful for setting the panel height initially, then disabling it once the height was set.  Simply to remove the guesswork / trial and error aspect.

**Comment by psifidotos** [comment]
@SteveKej , there is a discussion around: https://github.com/psifidotos/nowdock-plasmoid/issues/26

I am thinking that the Automatic mode would solve this... The user would set Automatic mode instead of the icon size and the panel will give the best in icon size based of the panels sizes and the zoom factor. This would also fix the issue that if there are too many items some of them become hidden or going out of the screen...

**Comment by SteveKej** [comment]
Interesting.  I suppose it would indeed solve the issue.

**Comment by psifidotos** [comment]
can you check the [automatic branch] for this please?
https://github.com/psifidotos/nowdock-panel/tree/automatic

**Comment by psifidotos** [comment]
https://bugs.kde.org/show_bug.cgi?id=368488

and also related to : https://github.com/psifidotos/nowdock-panel/issues/10

**Comment by SteveKej** [comment]
I've tried the automatic branch and whilst it seems to partly work, i'm experiencing some unexpected behaviour.  I'm still using the newbuffers branch of now dock, if that may have any bearing.
1.  Changing back and forth between automatic and fixed sizes sometimes stops working entirely.  The icon size doesn't change when the size buttons are clicked.  The change is recognised after restarting plasma.
2.  Sometimes plasma's panel settings bar (whatever it's called?) leaves an artifact behind when closed.
3.  I tested opening about 10  apps in addition to 8 launchers and the icons shrunk as expected, however when I closed the apps the launcher icons didn't return to their original size.  Again restarting plasma brought the original size back.

Cheers!

**Comment by psifidotos** [comment]
1. the icon sizes in the current implementation dont grow more than panel's size permits based on the zoom factor that has been set
2. it happens to me also some times... No idea at all...
3. this is interesting...

**Comment by SteveKej** [comment]
1.  I even tried this with plasma's panel at it's maximum height.  The buttons just stopped responding after a while.

**Comment by psifidotos** [comment]
https://github.com/psifidotos/nowdock-plasmoid/issues/58

**Comment by psifidotos** [comment]
this is in master....

https://github.com/psifidotos/nowdock-plasmoid/issues/58
