### ISSUE TITLE
Anchor configuration sometimes fails to be updated

### ISSUE THREAD

**Issue by kupiqu** [psifidotos/nowdock-panel#9]
I saw this behavior usuall when setting other than center in top/bottom options, not sure about left/right, didn't test.

**Comment by psifidotos** [comment]
is this in the latest master for both plasmoid and panel? I remember 
such a behavior only in the first version of Now Dock Panel...

What is your configuration for your panel concerning mimimumWidth, 
maximumWidth? Do you use all the screen size?

**Comment by kupiqu** [comment]
I'm using automatic and master branches respectively for panel and plasmoid (automatic because I'm testing this option).

Panel occupies full screen, icon size is set to 48 px, background set to 4 px.

Not sure what you mean about minimumWidth and maximumWidth.

**Comment by kupiqu** [comment]
Sorry, I checked it again and this seems to be fixed in current master version.

**Comment by psifidotos** [comment]
perfecto! 

development in rapid movement!!! :-)
